name: Trigger auto deployment for services-provider-container5

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/services-provider-container5-AutoDeployTrigger-21a2d73d-3be2-423d-8c6e-0900e0cc1247.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERVICESPROVIDERCONTAINER5_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: servicesprovideracr1.azurecr.io
          registryUsername: ${{ secrets.SERVICESPROVIDERCONTAINER5_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SERVICESPROVIDERCONTAINER5_REGISTRY_PASSWORD }}
          containerAppName: services-provider-container5
          resourceGroup: containerRG
          imageToBuild: servicesprovideracr1.azurecr.io/services-provider-container5:${{ github.sha }}
          
            

     

